name: Unit tests
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1]

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php-version }}
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: apcu bcmath gd intl pdo_mysql pcntl sodium
          args: --ignore-platform-reqs

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: apcu bcmath gd intl pdo_mysql pcntl sodium
          command: tests:unit
