name: Unit tests
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4, 8.0]

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-version }}-${{ matrix.composer-version }}

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          args: --ignore-platform-reqs

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          command: tests:unit
